# Generated by Django 3.2.4 on 2021-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_recipe_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='original_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
